_set = set()

n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)
n = int(input("enter number"))
_set.add(n)

print(_set)